using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pangya_MessengerServer.Flags
{
    public enum PacketIDClient
    {
        CLIENT_CONNECT_0x12 = 0x12,
        CLIENT_REQ_USERINFO_OFFLINE_0x13,
        CLIENT_REQ_USERINFO_0x14,
        CLIENT_NOTIFY_LOGOUT_0x16 = 0x16,
        CLIENT_REQ_CHECK_NICK_0x17,
        CLIENT_REQ_REGISTER_FRIEND_0x18,
        CLIENT_REQ_FRIEND_AGREE_0x19,
        CLIENT_REQ_FRIEND_BLOCK_0x1A,
        CLIENT_REQ_FRIEND_BLOCK_CANCEL_0x1B,
        CLIENT_REQ_FRIEND_REMOVE_0x1C,
        CLIENT_NOTIFY_UPDATE_MY_STATUS_0x1D,
        CLIENT_REQ_CHAT_FRIEND_0x1E,
        CLIENT_REQ_CHANGE_FRIENDALIAS_0x1F,
        CLIENT_REQ_UPDATE_CHANNEL_INFO_0x23 = 0x23,
        CLIENT_NOTIFY_PLAYER_WAS_INVITED_ROOM_0x24,
        CLIENT_REQ_CHAT_GUILD_0x25,
        CLIENT_NOTIFY_PLAYER_WAS_INVITED_ROOM_GUILD_BATTLE_0x28 = 0x28,
        CLIENT_NOTIFY_PLAYER_GIFT_ITEM_0x29,
        CLIENT_NOTIFY_PLAYER_GUILD_JOINED_0x2A,
        CLIENT_NOTIFY_PLAYER_GUILD_BANISH_0x2B,
        CLIENT_NOTIFY_PLAYER_GUILD_SHIELD_CHANGED_0x2C,
        CLIENT_NOTIFY_PLAYER_GUILD_NAME_CHANGED_0x2D,
    }

    public enum PacketIDServer //sub?
    {
        SERVER_NONE = 0x100,
        SERVER_USERINFO_OFFLINE = 0x101,
        SERVER_USERINFO = 0x102,
        SERVER_UNKNOWN = 0x103,
        SERVER_REGISTER_FRIEND = 0x104,
        SERVER_UNKNOWN_0x105 = 0x105,
        SERVER_NEW_FRIEND_MESSAGE = 0x106,
        SERVER_UNKNOWN_0x107 = 0x107,
        SERVER_UNKNOWN_0x108,
        SERVER_FRIEND_AGREE  = 0x109,
        SERVER_FRIEND_ACCEPTED = 0x10A,
        SERVER_FRIEND_REMOVE = 0x10B,
        SERVER_FRIEND_BLOCK = 0x10C,
        SERVER_FRIEND_BLOCK_CANCEL = 0x10D,
        SERVER_UNKNOWN_0x10E = 0x10E,
        SERVER_FRIEND_LOGOUT = 0x10F,
        SERVER_UNKNOWN_0x110 = 0x110,
        SERVER_UNKNOWN_0x112 = 0x112,
        SERVER_SEND_TALK = 0x113, // FRIEND OR GUILD
        SERVER_UNKNOWN_0x114 = 0x114,
        SERVER_CHANGE_MY_STATUS = 0x115,
        SERVER_UNKNOWN_0x116 = 0x116,
        SERVER_CHECK_NICK = 0x117,
        SERVER_UNKNOWN_0x118 = 0x118,
        SERVER_CHANGED_FRIENDALIAS = 0x119,
        SERVER_CONNECT = 0x2E, // RES == Msn
        SERVER_LOGIN_ACK = 0x2F,
        SERVER_FRIEND_AND_GUILD_LIST = 0x30
    }
}
