<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CS8603;CS8600;CS8601;CS8602;CS8618;IDE0290;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn>1701;1702;CS8603;CS8600;CS8601;CS8602;CS8618;IDE0290;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS8603;CS8600;CS8601;CS8602;CS8618;IDE0290;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn>1701;1702;CS8603;CS8600;CS8601;CS8602;CS8618;IDE0290;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PangyaAPI.DataBase\PangyaAPI.DataBase.csproj" />
    <ProjectReference Include="..\PangyaAPI.IFF\PangyaAPI.IFF.csproj" />
    <ProjectReference Include="..\PangyaAPI.Utilities\PangyaAPI.Utilities.csproj" />
  </ItemGroup>

</Project>
